%%BF 2016, written for a basic averaging command outside of a GUI
%Modified by Margo September 2016
% function averageTraces
figureofinterest=gcf;
h=findobj(figureofinterest, 'Type', 'line');
data=get(h, 'Ydata');

if iscell(data)
    arraydata=cell2mat(data);
    average=mean(arraydata,1);
else
    average=mean(data,1);
end
time = (0.1:0.1:length(average)/10)';

%% Added on 12th of Jan 2017 - find the dip and the slope and plot it all
    %% Settings
    displayResults = true;
    minimumDipSize = -20;
    slopeFitThresholdLower = 0.4;
    slopeFitThresholdUpper = 0.6;
%     removeBaselineDatapointsMoreThanNSigma = 2; % How many sigma you want to take with you
   % relevantDataStartTime = 0;
   % relevantDataEndTime = 600;
   % baselineStartTime = 480;
   % baselineEndTime = 500;
   % plotStartTime = 0;
   % plotEndTime = 600;
     %   removeBaselineDatapointsMoreThanNSigma = 2; % How many sigma you want to take with you
    relevantDataStartTime = 600;
    relevantDataEndTime = 620;
    baselineStartTime = 604;
    baselineEndTime = 605;
    plotStartTime = 550;
    plotEndTime = 700;
    %% Prepare Data
    relevantShortTime = time((time >= relevantDataStartTime) .* (time <= relevantDataEndTime) == 1);
    relevantShortData = average((time >= relevantDataStartTime) .* (time <= relevantDataEndTime) == 1);

    %% First, we find the peak 
    % Find the minima (maxima of data*-1)
    [Maxima,MaxIdx] = findpeaks(relevantShortData*(-1));

    % Select the peak - the first minimum that is smaller than the noise
    % threshold
    indexOfDip = -1;
    for i=1:numel(Maxima)
        if abs(Maxima(i)) > abs(minimumDipSize)
            indexOfDip = MaxIdx(i);
            break;
        end
    end

    if indexOfDip == -1
        figure;
        clf;
        hold on
        plot(relevantShortTime,relevantShortData,'magenta');
        title('No Peak found in this image');
        legend('off');
        error('No minimum foundQAQ')
    end

    valueOfDip = relevantShortData(indexOfDip);

    if displayResults
        disp(['Dip found at time ' num2str(relevantShortTime(indexOfDip)) ' with depth ' num2str(valueOfDip) '!']);
    end

    %% Find the slope and fit it
    startPoint = -1;
    endPoint = -1;
    for i=indexOfDip:-1:1
        if (endPoint == -1) && (abs(relevantShortData(i)) < abs(slopeFitThresholdUpper*valueOfDip))
            endPoint = i;
        end
        if (startPoint == -1) && (abs(relevantShortData(i)) < abs(slopeFitThresholdLower*valueOfDip))
            startPoint = i;
            break;
        end
    end

    if (startPoint == -1) || (endPoint == -1)
        figure;
        clf;
        hold on
        plot(relevantShortTime,relevantShortData,'black');
        plot(relevantShortTime(indexOfDip),valueOfDip,'Xb','MarkerSize',20);
        title('Slope not clear in this image');
        legend('off');
        error('Couldnt find starting point or end point for the slope!');
    end

    slopeTime = relevantShortTime(startPoint:endPoint);
    slopeData = relevantShortData(startPoint:endPoint);

    % Autogenerated fit by cftool
    [xData, yData] = prepareCurveData( slopeTime, slopeData' );
    % Set up fittype and options.
    ft = fittype( 'poly1' );
    opts = fitoptions( 'Method', 'LinearLeastSquares' );
    opts.Robust = 'Bisquare';
    % Fit model to data.
    [fitresult, ~] = fit( xData, yData, ft, opts );

    % The value we determined:
    slopeOfDip = fitresult.p1;

    if displayResults
        disp(['Slope found to be ' num2str(slopeOfDip) '!']);
    end
    
    %% Determine the baseline
    baselineData = average((time >= baselineStartTime) .* (time <= baselineEndTime) == 1);
    baselineTime = time((time >= baselineStartTime) .* (time <= baselineEndTime) == 1);
%     filteredBaseline = baselineData;
%     filteredBaseline(filteredBaseline>mean(filteredBaseline)+ ...
%         removeBaselineDatapointsMoreThanNSigma*std(filteredBaseline))=[];
    baseline = median(baselineData);
    if displayResults
        disp(['Baseline found to be ' num2str(baseline) '!']);
    end
    
    %% Plot results
    % We make this the nice picture, the next is the stuff to check if
    % everything is working
    figure;
    hold on
    relevantTime = time((time >= plotStartTime) .* (time <= plotEndTime) == 1);
    relevantData = average((time >= plotStartTime) .* (time <= plotEndTime) == 1);
    plot(relevantTime,relevantData,'blue','LineWidth',2);
    set(gca,'fontsize',14);
    xlabel('Time (ms)'), ylabel('Peak value (pA)');
    stringToDisplay = {['Peak: ' num2str(valueOfDip-baseline) ' pA'], ['Time: ' num2str(relevantShortTime(indexOfDip)) ' ms'], ['Slope: ' num2str(slopeOfDip) ' pA/ms']};
    text(plotEndTime-20,0.9*valueOfDip,stringToDisplay,'fontsize',10);
    
    figure;
    clf;
    hold on
    plot(relevantShortTime,relevantShortData,'black');
    plot(baselineTime,baselineData,'black');
    plot(fitresult);
    refline(0,baseline);
    plot(relevantShortTime(indexOfDip),valueOfDip,'Xb','MarkerSize',20);
    title('Ugly Plot so Margo can see if Stuff is working');
    xlim([min(baselineTime) max(relevantShortTime)]);
    ylim([1.2*valueOfDip 3*max(relevantShortData)]);
    legend('off');
% end
